# Generated by Django 5.2.8 on 2025-11-29 12:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=255, verbose_name='Producent samolotu')),
                ('aircraft_type', models.CharField(max_length=255, verbose_name='Typ samolotu')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='S/N samolotu')),
                ('registration_marks', models.CharField(max_length=20, unique=True, verbose_name='Znaki rejestracyjne')),
                ('next_service_date', models.DateField(blank=True, null=True, verbose_name='Data następnej obsługi')),
                ('next_service_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ilość nalotu następnej obsługi')),
                ('arc_valid_until', models.DateField(blank=True, null=True, verbose_name='Data ważności ARC')),
                ('insurance_valid_until', models.DateField(blank=True, null=True, verbose_name='Data ważności OC')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywny')),
            ],
            options={
                'verbose_name': 'Samolot',
                'verbose_name_plural': 'Samoloty',
                'ordering': ['registration_marks'],
            },
        ),
        migrations.CreateModel(
            name='PDTPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdt_date', models.DateField(verbose_name='Data PDT')),
                ('page_number', models.CharField(max_length=50, verbose_name='Nr. Strony PDT')),
                ('persons_on_board', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Ilość osób na pokładzie')),
                ('fuel_added', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Paliwo dodane')),
                ('fuel_at_start', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Paliwo do startu')),
                ('oil_added', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Olej dodany')),
                ('oil_at_start', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Olej do startu')),
                ('last_operation_notes', models.TextField(blank=True, default='', verbose_name='Uwagi do ostatniej operacji lotniczej')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pdt_pages', to='app.aircraft', verbose_name='Samolot')),
            ],
            options={
                'verbose_name': 'Strona PDT',
                'verbose_name_plural': 'Strony PDT',
                'ordering': ['-pdt_date', '-page_number'],
            },
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=100, unique=True, verbose_name='Nr. Licencji')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Nr. Telefonu')),
                ('sepl_valid_until', models.DateField(blank=True, null=True, verbose_name='Data ważności SEPL(A)')),
                ('medical_valid_until', models.DateField(blank=True, null=True, verbose_name='Data ważności badań MED.')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pilot_profile', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Pilot',
                'verbose_name_plural': 'Piloci',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='FlightOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.TimeField(verbose_name='Czas startu')),
                ('departure_location', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Kod ICAO miejsca startu musi składać się z 4 wielkich liter', regex='^[A-Z]{4}$')], verbose_name='Miejsce startu (ICAO)')),
                ('landing_time', models.TimeField(verbose_name='Czas lądowania')),
                ('landing_location', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Kod ICAO miejsca lądowania musi składać się z 4 wielkich liter', regex='^[A-Z]{4}$')], verbose_name='Miejsce lądowania (ICAO)')),
                ('number_of_landings', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Ilość lądowań')),
                ('flight_time', models.DurationField(help_text='Obliczany automatycznie jako różnica między czasem lądowania a czasem startu', verbose_name='Czas lotu')),
                ('engine_hours_after_flight', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Licznik motogodzin po locie')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
                ('pdt_page', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flight_operations', to='app.pdtpage', verbose_name='Strona PDT')),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flight_operations', to='app.pilot', verbose_name='Pilot')),
            ],
            options={
                'verbose_name': 'Operacja lotnicza',
                'verbose_name_plural': 'Operacje lotnicze',
                'ordering': ['-pdt_page__pdt_date', 'departure_time'],
            },
        ),
        migrations.AddConstraint(
            model_name='pdtpage',
            constraint=models.UniqueConstraint(fields=('aircraft', 'page_number'), name='unique_aircraft_pdt_page'),
        ),
        migrations.AddConstraint(
            model_name='flightoperation',
            constraint=models.CheckConstraint(condition=models.Q(('number_of_landings__gte', 1)), name='min_one_landing'),
        ),
    ]
