# Generated by Django 5.2.8 on 2025-12-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='aircraft_photos/', verbose_name='Zdjęcie samolotu'),
        ),
        migrations.AddField(
            model_name='pdtpage',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='pdt_photos/', verbose_name='Zdjęcie PDT'),
        ),
    ]
