# Generated by Django 5.2.8 on 2025-12-13 20:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_aircraft_photo_pdtpage_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='base_flight_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Wartość początkowa godzin nalotu (np. przy zakupie samolotu)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Bazowa liczba godzin nalotu'),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='base_landings',
            field=models.PositiveIntegerField(default=0, help_text='Wartość początkowa liczby lądowań (np. przy zakupie samolotu)', verbose_name='Bazowa liczba lądowań'),
        ),
    ]
