# Generated by Django 5.2.8 on 2026-04-17 14:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_aircraft_base_flight_hours_aircraft_base_landings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='base_flight_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Wartość początkowa godzin nalotu', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Bazowa liczba godzin nalotu'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='base_landings',
            field=models.PositiveIntegerField(default=0, help_text='Wartość początkowa liczby lądowań', verbose_name='Bazowa liczba lądowań'),
        ),
        migrations.CreateModel(
            name='AircraftReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(verbose_name='Od')),
                ('end_datetime', models.DateTimeField(verbose_name='Do')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Uwagi')),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='app.aircraft', verbose_name='Samolot')),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='app.pilot', verbose_name='Pilot')),
            ],
            options={
                'verbose_name': 'Rezerwacja samolotu',
                'verbose_name_plural': 'Rezerwacje samolotów',
                'ordering': ['start_datetime'],
            },
        ),
    ]
