# Generated by Django 5.2.8 on 2026-05-14 17:44

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_aircraft_show_in_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.aircraft_photo_path, verbose_name='Zdjęcie samolotu'),
        ),
        migrations.AlterField(
            model_name='pdtpage',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.pdt_photo_path, verbose_name='Zdjęcie PDT'),
        ),
    ]
